-- =============================================================================
-- PROPOSITION — LOT 10, CE QUI RESTE : cinq copies de données personnelles
--                hors de tout périmètre de purge
--
--   *** NON APPLIQUÉE. NE PAS EXÉCUTER SANS DÉCISION FONDATEUR. ***
--
-- Fichier volontairement NON horodaté : `supabase db push` l'ignore.
-- =============================================================================
--
-- CE QUI EST DÉJÀ FAIT
--
-- La partie principale du lot 10 est APPLIQUÉE, le 28/07/2026 :
-- `20260728161513_l10_purge_coach_payout_details.sql` — un IBAN survivait à la
-- suppression du compte. Voir ce fichier pour la méthode et les vérifications.
--
-- La couverture est passée de 60/28 à 60/27 sur les 88 couples (table, colonne)
-- qui référencent `public.users`. Les 27 restants sont tous justifiés par la
-- matrice de purge : rétention comptable de dix ans, colonnes d'acteur
-- administratif conservées, capitanat d'équipe.
--
-- Il reste un point, et il ne se tranche pas par une requête.
--
-- =============================================================================
-- LES CINQ COPIES DE SAUVEGARDE
-- =============================================================================
--
--   _backup_sessions_20260719          44 lignes
--   _backup_weather_20260719           14
--   _backup_registrations_20260719      5
--   _backup_payments_20260719           2
--   _backup_session_feedback_20260719   0
--
-- La matrice de purge en cite DEUX (`_backup_sessions`, `_backup_registrations`)
-- et les marque « à DROP après vérification, décision fondateur ». Il y en a
-- cinq — dont `_backup_payments`, qui n'était pas listée.
--
-- CE N'EST PAS UNE EXPOSITION. Vérifié le 28/07/2026 : aucune de ces tables
-- n'accorde SELECT à `anon` ni à `authenticated`. Le GRANT est absent, donc
-- PostgREST ne les sert pas — que la RLS soit active ou non, et quatre l'ont
-- désactivée. Seul `service_role` y accède.
--
-- C'est un défaut d'EFFACEMENT : un compte purgé survit dans ces copies, et
-- `purge_user_data` ne les touche pas.
--
-- -----------------------------------------------------------------------------
-- DEUX ISSUES, À VOTRE MAIN
-- -----------------------------------------------------------------------------
--
-- 1. LES SUPPRIMER, si elles ont fini de servir. Elles datent du 19/07/2026,
--    posées en filet pendant SEC-1 — il y a neuf jours.
--
--      DROP TABLE IF EXISTS public._backup_sessions_20260719;
--      DROP TABLE IF EXISTS public._backup_registrations_20260719;
--      DROP TABLE IF EXISTS public._backup_payments_20260719;
--      DROP TABLE IF EXISTS public._backup_session_feedback_20260719;
--      DROP TABLE IF EXISTS public._backup_weather_20260719;
--
--    *** Une suppression ne se reprend pas. Vérifiez d'abord qu'elles ne
--        servent plus — je ne peux pas le savoir d'ici. ***
--
-- 2. LES GARDER et les inclure dans la purge : cinq tables de plus dans une
--    fonction déjà longue, pour un filet de neuf jours.
--
-- La première est la plus propre SI le filet a fait son office.
--
-- =============================================================================
-- CE QUI N'EST TOUJOURS PAS PROUVÉ
-- =============================================================================
--
-- La vérification de couverture est TEXTUELLE : elle établit qu'une colonne est
-- citée dans une instruction visant sa table, pas que le prédicat est juste.
--
-- La preuve complète est celle que demande le plan : créer un compte, produire
-- de la donnée partout, purger, vérifier qu'il ne reste rien. Elle ne peut pas
-- tourner en production — il faut une branche Supabase, qui se facture.
-- Décision fondateur, non prise.
-- =============================================================================
