-- ============================================================================
-- PROPOSITION — L-21s : suppression de la table `duels`
-- ============================================================================
--
-- ⚠️  NON APPLIQUÉE. Nommée `PROPOSITION_` et non horodatée : elle n'est PAS
--     ramassée par `supabase db push`. Supprimer une table de production demande
--     l'accord explicite du fondateur (CLAUDE.md).
--
-- ⚠️  RÈGLE 0.5 DU PLAN DE MONTAGE — À LIRE AVANT D'APPLIQUER
--     Aucune suppression destructive ne part avant qu'une sauvegarde vérifiée
--     existe. Même avec l'accord, ce fichier attend cette vérification. Une
--     table vide reste une décision irréversible.
--
-- ----------------------------------------------------------------------------
-- POURQUOI ELLE DOIT PARTIR — C'EST DOCTRINAL, PAS TECHNIQUE
-- ----------------------------------------------------------------------------
--
-- Le plan : *« Suppression de `duels` — zéro ligne, zéro perte. La table portait
-- un `status` et un `resolved_at` : un défi qui se résout, donc un vainqueur. »*
--
-- C'est tout l'argument. Une table qui sait qu'un affrontement se « résout »
-- porte l'idée qu'il y a un gagnant, et la doctrine OXV interdit tout classement
-- entre pilotes. Le schéma décrit une intention que le produit refuse.
--
-- La laisser vide n'est pas neutre : elle rouvrira la question à chaque
-- relecture du schéma, et un jour quelqu'un la remplira.
--
-- ----------------------------------------------------------------------------
-- CE QUI A ÉTÉ VÉRIFIÉ AVANT DE PROPOSER
-- ----------------------------------------------------------------------------
--
--   · `select count(*) from duels` → **0 ligne**, le 29/07/2026.
--   · Aucun lecteur : zéro `.from('duels')` dans `src/`, `app/` et
--     `supabase/functions/`.
--   · **Le piège de nom est levé** : `duelService.ts` porte le mot mais lit
--     `app_session_analyses` sous RLS d'amitié. Il ne touche pas cette table et
--     survivra à sa suppression. Ne pas le renommer dans la même passe — un
--     renommage et une suppression dans un même lot rendent la relecture
--     illisible.
--
-- ----------------------------------------------------------------------------
-- CE QUI REMPLACE LE BESOIN, ET QUI EXISTE DÉJÀ
-- ----------------------------------------------------------------------------
--
-- Le plan tranche aussi la suite : *« Aucune table de comparaison n'est créée —
-- elle est éphémère, sans trace. L'amitié EST le consentement : `are_friends()`
-- exige déjà `accepted` des deux côtés. »*
--
-- La comparaison entre amis ne laisse donc rien derrière elle. C'est le
-- contraire d'un duel : on regarde ensemble, on ne conserve pas de verdict.
--
-- ----------------------------------------------------------------------------

begin;

-- `cascade` retire aussi les policies, index et contraintes portés par la
-- table. Aucune autre table ne la référence — vérifié : aucune clé étrangère
-- entrante.
drop table if exists public.duels cascade;

commit;
